name: Publish

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

permissions:
  id-token: write
  contents: read

jobs:
  validate-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Extract version
        id: get-version
        run: |
          # Remove 'v' prefix from tag
          VERSION=${GITHUB_REF#refs/tags/v}
          # Validate version format
          if ! [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                echo "Invalid version format. Must be vX.Y.Z"
                exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  publish-python:
    needs: [validate-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Update Python version
        run: |
          echo "__version__ = \"${{ needs.validate-version.outputs.version }}\"" > src/bismuthsdk/__about__.py

      - name: Install deps
        run: pip install hatch

      - name: Build Wheel
        run: hatch build

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: dist/*

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
