name: Test Python

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  mypy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install hatch
        run: |
          pip install hatch

      - name: Run mypy
        run: |
          hatch run types:check

  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install hatch
        run: |
          pip install hatch

      - name: Run pytest with coverage
        run: |
          hatch test --cov

      - name: Create HTML coverage report
        if: always()
        run: |
          hatch -e hatch-test.py3.10 run coverage html
          tar -czf htmlcov.tar.gz htmlcov

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: python/htmlcov.tar.gz
