name: Test

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install hatch
        run: |
          pip install hatch
          
      - name: Run mypy
        run: |
          hatch run types:check
