name: Test Node

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  jest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node/bismuthsdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          npm install

      - name: Start Wiremock
        run: |
          docker run -d --rm \
            -p 9090:8080 \
            --name wiremock \
            -v $GITHUB_WORKSPACE/testing:/home/wiremock/mappings \
            wiremock/wiremock:3.12.1

      - name: Jest
        run: |
          npm test
